CREATE TABLE "users" (
  "id" VARCHAR(250) PRIMARY KEY NOT NULL UNIQUE,
  "name" VARCHAR(250) NOT NULL,
  "email" VARCHAR(250) NOT NULL UNIQUE,
  "username" VARCHAR(250) NOT NULL UNIQUE,
  "password" VARCHAR(250) NOT NULL
)